name: Docker Build CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test build Docker Image
        run: |
          docker build -t my-first-web-app:test .
          echo "Docker image built successfully!"
